services:
  postgres:
    image: postgres:16-alpine
    container_name: social-pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: social
      POSTGRES_PASSWORD: social
      POSTGRES_DB: social
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
